export { default as mainConfig } from './main'
export { default as reCaptchaConfig } from './reCaptcha'
export { default as themeConfig } from './theme'
export { default as seoConfig } from './seo'
export { default as i18nConfig } from './i18n'
export { default as graphqlConfig } from './graphqlConfig'
